from __future__ import annotations

import json
import re
from textwrap import dedent

DEFAULT_ONBOARDING_PORT = 8000
DEFAULT_WORKSPACE_ROOT_CONTAINER = "/workspace"
DEFAULT_ONBOARDING_DENY_PATTERNS = ".git/objects,.env,.env.local,.env.production,.venv,node_modules"


def normalize_workspace_host_path(workspace_host: str) -> str:
    value = workspace_host.strip()
    if re.match(r"^[A-Za-z]:[\\/]", value) or value.startswith("\\\\"):
        return value.replace("\\", "/")
    return value


def docker_compose_override(workspace_host: str, workspace_root_container: str, *, read_only: bool = True) -> str:
    normalized_host = normalize_workspace_host_path(workspace_host)
    suffix = ":ro" if read_only else ""
    return dedent(f"""\
        # Automatically generated by scripts/hivemind_init.py
        # Bindet den externen Workspace als Volume in den backend-Container.
        # Commit diese Datei NICHT ins Hivemind-Repo — sie ist workspace-spezifisch.
        services:
          backend:
            volumes:
              - "{normalized_host}:{workspace_root_container}{suffix}"
            environment:
              HIVEMIND_WORKSPACE_ROOT: "{workspace_root_container}"
    """)


def vscode_mcp_json(port: int) -> str:
    config = {
        "servers": {
            "hivemind": {
                "type": "sse",
                "url": f"http://localhost:{port}/api/mcp/sse",
            }
        }
    }
    return json.dumps(config, indent=2) + "\n"


def cursor_mcp_json(port: int) -> str:
    config = {
        "mcpServers": {
            "hivemind": {
                "type": "sse",
                "url": f"http://localhost:{port}/api/mcp/sse",
            }
        }
    }
    return json.dumps(config, indent=2) + "\n"


def hivemind_config_yml(
    workspace_host: str,
    workspace_root_container: str,
    port: int,
    deny_patterns: str,
) -> str:
    normalized_host = normalize_workspace_host_path(workspace_host)
    return dedent(f"""\
        # Hivemind Workspace-Konfiguration
        # Generiert von scripts/hivemind_init.py
        #
        # Diese Datei beschreibt, wie Hivemind dieses Repository analysiert.
        # Optional: ins Repo committen, um Einstellungen zu teilen.

        hivemind:
          server_url: "http://localhost:{port}/api/mcp/sse"

          workspace:
            host_path: "{normalized_host}"
            container_path: "{workspace_root_container}"
            deny_patterns: "{deny_patterns}"

          ide:
            vscode:
              mcp_config: ".vscode/mcp.json"
            cursor:
              mcp_config: ".cursor/mcp.json"
    """)
