#!/usr/bin/env python3
"""hivemind init — Konfiguration für externe Repos.

Generiert:
  - docker-compose.override.yml  (Workspace-Mount in den backend-Container)
  - .vscode/mcp.json             (Copilot Agent Mode — MCP-Server-Eintrag)
  - .hivemind/config.yml         (Workspace-Einstellungen)

Verwendung (vom hivemind-Projekt-Root aus):
  python scripts/hivemind_init.py --workspace /path/to/your/repo
  python scripts/hivemind_init.py --workspace /path/to/your/repo --port 8000 --dry-run

Die generierten Dateien werden im Verzeichnis des hivemind-Repos abgelegt
(docker-compose.override.yml) bzw. im Ziel-Workspace (.vscode/, .hivemind/).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from textwrap import dedent

# ── Defaults ──────────────────────────────────────────────────────────────

DEFAULT_PORT = 8000
DEFAULT_WORKSPACE_ROOT_CONTAINER = "/workspace"
DEFAULT_DENY_PATTERNS = ".git/objects,.env,.env.local,.env.production,.venv,node_modules"


# ── Generators ────────────────────────────────────────────────────────────

def _docker_compose_override(workspace_host: str, workspace_root_container: str) -> str:
    """docker-compose.override.yml — bindet das externe Repo als /workspace ein."""
    return dedent(f"""\
        # Automatically generated by scripts/hivemind_init.py
        # Bindet den externen Workspace als Read-Only-Volume in den backend-Container.
        # Commit diese Datei NICHT ins Hivemind-Repo — sie ist workspace-spezifisch.
        services:
          backend:
            volumes:
              - {workspace_host}:{workspace_root_container}:ro
            environment:
              HIVEMIND_WORKSPACE_ROOT: "{workspace_root_container}"
    """)


def _vscode_mcp_json(port: int) -> str:
    """VS Code / Copilot Agent Mode — .vscode/mcp.json."""
    config = {
        "servers": {
            "hivemind": {
                "type": "sse",
                "url": f"http://localhost:{port}/api/mcp/sse"
            }
        }
    }
    return json.dumps(config, indent=2) + "\n"


def _hivemind_config_yml(
    workspace_host: str,
    workspace_root_container: str,
    port: int,
    deny_patterns: str,
) -> str:
    """.hivemind/config.yml — Workspace-Einstellungen."""
    return dedent(f"""\
        # Hivemind Workspace-Konfiguration
        # Generiert von scripts/hivemind_init.py
        #
        # Diese Datei beschreibt, wie Hivemind dieses Repository analysiert.
        # Optional: ins Repo committen, um Einstellungen zu teilen.

        hivemind:
          # URL des Hivemind-MCP-Servers
          server_url: "http://localhost:{port}/api/mcp/sse"

          workspace:
            # Host-Pfad zum Workspace (wird als Volume in den Container gemountet)
            host_path: "{workspace_host}"

            # Container-interner Pfad (entspricht HIVEMIND_WORKSPACE_ROOT)
            container_path: "{workspace_root_container}"

            # Kommagetrennte Muster — diese Pfade werden vom Analyzer ignoriert
            # Umgebungsvariable: HIVEMIND_FS_DENY_LIST
            deny_patterns: "{deny_patterns}"

          # IDE-Integration
          ide:
            vscode:
              mcp_config: ".vscode/mcp.json"
            cursor:
              mcp_config: ".cursor/mcp.json"
    """)


def _cursor_mcp_json(port: int) -> str:
    """Cursor IDE — .cursor/mcp.json."""
    config = {
        "mcpServers": {
            "hivemind": {
                "type": "sse",
                "url": f"http://localhost:{port}/api/mcp/sse"
            }
        }
    }
    return json.dumps(config, indent=2) + "\n"


# ── Writer ────────────────────────────────────────────────────────────────

def _write(path: Path, content: str, dry_run: bool) -> None:
    """Schreibt Datei — oder gibt Vorschau aus bei dry_run."""
    if dry_run:
        print(f"\n{'='*60}")
        print(f"[DRY-RUN] Würde schreiben: {path}")
        print('='*60)
        print(content)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        print(f"  ⚠️  Überschreibe: {path}")
    else:
        print(f"  ✅  Erstelle:    {path}")
    path.write_text(content, encoding="utf-8")


# ── Main ──────────────────────────────────────────────────────────────────

def main() -> None:
    ap = argparse.ArgumentParser(
        description="Hivemind init — Workspace-Konfiguration für externe Repos",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=dedent("""\
            Beispiele:
              python scripts/hivemind_init.py --workspace /path/to/myproject
              python scripts/hivemind_init.py --workspace /path/to/myproject --port 8001 --dry-run
              python scripts/hivemind_init.py --workspace /path/to/myproject --vscode-only
        """),
    )
    ap.add_argument(
        "--workspace", "-w",
        required=True,
        help="Absoluter Pfad zum externen Repository (Host-Pfad).",
    )
    ap.add_argument(
        "--container-path",
        default=DEFAULT_WORKSPACE_ROOT_CONTAINER,
        help=f"Container-interner Pfad (HIVEMIND_WORKSPACE_ROOT). Default: {DEFAULT_WORKSPACE_ROOT_CONTAINER}",
    )
    ap.add_argument(
        "--port", "-p",
        type=int,
        default=DEFAULT_PORT,
        help=f"Port des Hivemind-MCP-Servers. Default: {DEFAULT_PORT}",
    )
    ap.add_argument(
        "--deny-patterns",
        default=DEFAULT_DENY_PATTERNS,
        help="Kommagetrennte Deny-Patterns. Default: .git/objects,.env,...",
    )
    ap.add_argument(
        "--output-dir",
        default=None,
        help="Hivemind-Root-Verzeichnis für docker-compose.override.yml. "
             "Default: aktuelles Verzeichnis.",
    )
    ap.add_argument(
        "--vscode-only",
        action="store_true",
        help="Nur .vscode/mcp.json im Workspace generieren (kein docker-compose.override.yml).",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="Keine Dateien schreiben — nur Vorschau ausgeben.",
    )
    args = ap.parse_args()

    workspace_host = str(Path(args.workspace).resolve())
    container_path = args.container_path
    port = args.port
    deny_patterns = args.deny_patterns
    hivemind_root = Path(args.output_dir).resolve() if args.output_dir else Path.cwd()
    workspace_path = Path(workspace_host)
    dry_run: bool = args.dry_run

    print(f"\n🐝  Hivemind Init")
    print(f"   Workspace:       {workspace_host}")
    print(f"   Container-Pfad:  {container_path}")
    print(f"   MCP-Port:        {port}")
    print(f"   Hivemind-Root:   {hivemind_root}")
    print()

    if not workspace_path.is_dir() and not dry_run:
        print(f"❌  Fehler: Workspace nicht gefunden: {workspace_host}", file=sys.stderr)
        sys.exit(1)

    # 1. docker-compose.override.yml (im hivemind-Root)
    if not args.vscode_only:
        override_path = hivemind_root / "docker-compose.override.yml"
        _write(
            override_path,
            _docker_compose_override(workspace_host, container_path),
            dry_run,
        )

    # 2. .vscode/mcp.json (im Ziel-Workspace)
    _write(
        workspace_path / ".vscode" / "mcp.json",
        _vscode_mcp_json(port),
        dry_run,
    )

    # 3. .cursor/mcp.json (im Ziel-Workspace)
    _write(
        workspace_path / ".cursor" / "mcp.json",
        _cursor_mcp_json(port),
        dry_run,
    )

    # 4. .hivemind/config.yml (im Ziel-Workspace)
    _write(
        workspace_path / ".hivemind" / "config.yml",
        _hivemind_config_yml(workspace_host, container_path, port, deny_patterns),
        dry_run,
    )

    if not dry_run:
        print()
        print("✅  Setup abgeschlossen!")
        print()
        print("Nächste Schritte:")
        print(f"  1. Hivemind stack neu starten:  make down && make up")
        print(f"  2. Backend prüfen:              curl http://localhost:{port}/health")
        print(f"  3. VS Code öffnen → Copilot Agent Mode aktivieren")
        print(f"  4. Discovery-Endpoint prüfen:   curl http://localhost:{port}/api/mcp/discovery")
        print()
        print("Dokumentation: docs/setup-external-repo.md")


if __name__ == "__main__":
    main()
